# Generated by Django 4.2.1 on 2024-04-11 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_1994',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_1995',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_1996',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_1997',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_1998',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_1999',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2000',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2001',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2002',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2003',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2004',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2005',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2006',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2007',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2008',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2009',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2010',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2011',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2012',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2013',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='ep_2014',
        ),
        migrations.AlterField(
            model_name='countrymetadata',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='epdata.countrydata'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='epdata.countrydata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('consumption', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electric_consumptions', to='epdata.countrydata')),
            ],
        ),
    ]
