# Generated by Django 4.2.1 on 2024-04-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epdata', '0003_countrydata_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
