# Generated by Django 4.2.1 on 2024-04-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epdata', '0004_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epdata.countrydata'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
